### ISSUE TITLE
Validation should not give an error when the DOI is not filled in

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#495] opened 2020-03-26 15:58 UTC
Validation should not give an error when the DOI is not filled in. Or a clearer message for the user could be displayed like "The contribution DOI reference has not been set". The current error is confusing as people don't generally set the reference column in the contribution table when uploading data.
<img width="893" alt="Screen Shot 2020-03-26 at 8 53 09 AM" src="https://user-images.githubusercontent.com/1278789/77667574-a334f100-6f3f-11ea-9149-7c136bd81c94.png">

**Comment by rminnett** [comment] 2020-04-03 00:01
It's necessary for the validation to block making a private contribution public if it's missing a reference in the contribution table, but the error should be better than the standard "table is missing required column".

**Comment by rminnett** [comment] 2020-04-03 00:02
Closing as a duplicate of #491

**Closed by rminnett** 2020-04-03 00:02 UTC
Labels: Priority - 2, Problem - 2
