### ISSUE TITLE
Tried to update earthref.org/MagIC/12463 and failed

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#113] opened 2017-06-23 21:20 UTC
I dowloaded earthref.org/MagIC/12463 and then tried to update with the downloaded file. I can get it to the private workspace but the Activate button is not active due to no finding the DOI (It is red, anyway but the DOI is correct).
![screen shot 2017-06-23 at 2 17 35 pm](https://user-images.githubusercontent.com/1278789/27500807-f4076eea-581e-11e7-8b11-851d47264d86.png)

**Comment by rminnett** [comment] 2017-06-25 05:58
I think this is a bug caused by not checking the DOI automatically when updating (it fills in the DOI, but doesn't check CrossRef for the metadata). I think for an update, I can safely disable that edit box (if someone is updating, they shouldn't be able to accidentally change the DOI to assign it to a different reference) and enable the Activate button right away. This will also temporarily solve the issue of updating existing contributions that don't have a DOI.

**Comment by rminnett** [comment] 2017-06-25 05:59
For now, if it has a DOI like this one, I think you might be able to type a space after the DOI and trigger it to fetch the metadata from CrossRef and enable the Activate button.

**Comment by njarboe** [comment] 2017-06-27 03:54
Adding the space works. Great. But no one will guess to do this. We could add text explaining what to do or make it work quickly.

**Comment by rminnett** [comment] 2017-06-27 03:55
Good, at least I know what the problem is then - I can fix that tonight.

**Closed** 2017-06-27 16:52 UTC
Labels: Bug, Critical
