### ISSUE TITLE
Don't show higher level count when it is one

### ISSUE THREAD

**Issue by njarboe** [earthref/MagIC#270] opened 2017-09-29 23:35 UTC
Don't show higher level count when on lower level. A bunch of ones looks off.
![screen shot 2017-09-29 at 4 36 16 pm](https://user-images.githubusercontent.com/1278789/31039664-54b30300-a534-11e7-98d5-f61c13567eaa.png)

**Comment by rminnett** [comment] 2017-09-30 00:43
Duplicate of #190

**Closed by rminnett** 2017-09-30 00:43 UTC
Labels: Problem - 4, UI
