### ISSUE TITLE
wrong metadata in Private contribution summaries

### ISSUE THREAD

**Issue by ltauxe** [earthref/MagIC#384] opened 2018-11-19 22:21 UTC
I just uploaded a corrected version of the Snake River Plain (Tauxe et al., 2004, doi:10.1029/2003GC000661).  When I look on my Private Workspace, it shows the activated version, but all the meta data are incorrect.  (this in Idaho - not the Indian Ocean, for example).  

![screen shot 2018-11-19 at 10 37 13 am](https://user-images.githubusercontent.com/174861/48738586-55e79780-ec06-11e8-8ac3-7098a91ce44b.png)

**Comment by ltauxe** [comment] 2018-11-19 22:22
sorry wrong screenshot...   
![screen shot 2018-11-19 at 2 18 31 pm](https://user-images.githubusercontent.com/174861/48738639-7dd6fb00-ec06-11e8-9d5a-f7a629250399.png)

**Comment by rminnett** [comment] 2018-11-20 05:00
I think this is a duplicate of Lori's #383.

**Closed by rminnett** 2018-11-20 05:00 UTC
